version: '3'
services:
  app:
    container_name: 'articles'
    image: 'rreshrr/articles:latest'
    build: ./
    ports:
      - 1125:1125
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=data
      - SPRING_DATASOURCE_PASSWORD=data
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  postgres:
    image: 'postgres:13.1-alpine'
    container_name: 'postgresqldb'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_PASSWORD=data'
      - 'POSTGRES_USER=data'
